# Une makefile pour la version de base du minishell.

# La liste des fichiers sources
L = cn-decouper.c co-main.c

minishell: $L
	gcc -g -Wall $L -o minishell

clean:
	rm -fr a.out core core.* *.core *.o minishell
